name: Yew.rs CI
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: angeldollface/yew-github-pages-deploy@v1.0.0
        with:
          custom-config: true 
          config-path: './trunk.toml'
          deploy: true
          branch: 'gh-pages'
